# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/payments-management

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}


      - run: eval "echo $"${SONAR_PROJECT_KEY}""
      - run: eval "echo $"${SONAR_ORGANIZATION}""
      - run: eval "echo $"${SONAR_HOST}""
      - run: eval "echo $"${SONAR_LOGIN}""
      - run: eval "echo $"${GITHUB_TOKEN}""
      - run: eval "echo $"${CIRCLE_BRANCH}""
      - run: eval "echo $"${CIRCLE_PR_NUMBER}""
      - run:
          name: Set PR number
          command: |
            echo 'export CIRCLE_PR_NUMBER="${CIRCLE_PR_NUMBER:-${CIRCLE_PULL_REQUEST##*/}}"' >> $BASH_ENV
            source $BASH_ENV
            echo $CIRCLE_PR_NUMBER

      # run tests!
      - run: gradle test
      - run: gradle jacocoTestReport sonarqube  -Dsonar.projectKey=${SONAR_PROJECT_KEY}  -Dsonar.organization=${SONAR_ORGANIZATION}  -Dsonar.host.url=${SONAR_HOST}  -Dsonar.login=${SONAR_LOGIN}  -Dsonar.pullrequest.vsts.token.secured=${GITHUB_TOKEN}  -Dsonar.pullrequest.base=master -Dsonar.pullrequest.branch=${CIRCLE_BRANCH}  -Dsonar.pullrequest.key=${CIRCLE_PR_NUMBER} -Dsonar.pullrequest.provider=GitHub -Dsonar.pullrequest.github.repository=yurizp/payments-management